<?php
$app = "a Performance Machine";
?>
<div id="content-wrapper">
    <section class="indent">
        <div class="container">
            <div class="grid_12">
                <h1>Termos de Serviço</h1>   

                <p><em>Última modificação: 30 de abril de 2013</em></p>   

                <h2>Bem-vindo <?php echo $app ?>!</h2>
                <p>Agradecemos por usar nossos produtos e serviços.</p>
                <p>Ao usar nossos Serviços, você está concordando com estes termos. <b>Leia-os com atenção.</b></p>
                <p>Nossos Serviços são muito diversos, portanto, às vezes, podem aplicar-se termos adicionais ou exigências de produtos (inclusive exigências de idade). Os termos adicionais estarão disponíveis com os Serviços relevantes e esses termos adicionais se tornarão parte de nosso contrato com você, caso você use esses Serviços.</p>

                <h2 id="toc-services">Como usar nossos Serviços</h2>
                <p>É preciso que você siga as políticas disponibilizadas a você dentro dos Serviços.</p>
                <p>Não faça uso indevido de nossos Serviços. Por exemplo, não interfira com nossos Serviços nem tente acessá-los por um método diferente da interface e das instruções que fornecemos. Você pode usar nossos serviços somente conforme permitido por lei, inclusive leis e regulamentos de controle de exportação e reexportação. Podemos suspender ou deixar de fornecer nossos Serviços se você descumprir nossos termos ou políticas ou se estivermos investigando casos de suspeita de má conduta.</p>
                <p>O uso de nossos Serviços não lhe confere a propriedade sobre direitos de propriedade intelectual sobre os nossos Serviços ou sobre o conteúdo que você acessar. Você não pode usar conteúdos de nossos Serviços a menos que obtenha permissão do proprietário de tais conteúdos ou que o faça por algum meio permitido por lei. Estes termos não conferem a você o direito de usar quaisquer marcas ou logotipos utilizados em nossos Serviços. Não remova, oculte ou altere quaisquer avisos legais exibidos em ou junto a nossos Serviços.</p>
                <p>Nossos Serviços exibem alguns conteúdos que não são d<?php echo $app ?>. Esses conteúdos são de exclusiva responsabilidade da entidade que os disponibiliza. Podemos revisar conteúdo para determinar se é ilegal ou se infringe nossas políticas, e podemos remover ou nos recusar a exibir conteúdos que razoavelmente acreditamos violar nossas políticas ou a lei. Mas isso não significa, necessariamente, que revisaremos conteúdos, portanto por favor, não presuma que o faremos.</p>
                <p>Em relação com seu uso dos Serviços, podemos enviar-lhe anúncios de serviços, mensagens administrativas e outras informações. Você pode desativar algumas dessas comunicações.</p>

                <h2 id="toc-account">Sua Conta d<?php echo $app ?></h2>
                <p>Você precisa criar uma Conta d<?php echo $app ?> para utilizar alguns dos nossos Serviços. Você poderá criar sua própria Conta d<?php echo $app ?> ou sua Conta d<?php echo $app ?> poderá ser atribuída a você por um administrador, como seu empregador ou instituição de ensino. Se você estiver usando uma Conta d<?php echo $app ?> atribuída a você por um administrador, termos diferentes ou adicionais podem aplicar-se e seu administrador poderá ser capaz de acessar ou desativar sua conta.</p>
                <p>Caso tenha conhecimento de qualquer uso não autorizado de sua senha ou conta, <a href="<?php echo Yii::app()->createUrl('site/contact') ?>">entre em contato conosco</a>.</p>

                <h2 id="toc-protection">Proteção à Privacidade e aos Direitos Autorais</h2>
                <p>As <a href="<?php echo Yii::app()->createUrl('site/page', array('view' => 'privacy')) ?>">Políticas de Privacidade</a> d<?php echo $app ?> explicam o modo como tratamos seus dados pessoais e protegemos sua privacidade quando você usa nossos Serviços. Ao utilizar nossos Serviços, você concorda que <?php echo $app ?> poderá usar esses dados de acordo com nossas políticas de privacidade.</p>
                <p>Nós respondemos às notificações de alegação de violação de direitos autorais e encerramos contas de infratores reincidentes de acordo com os procedimentos estabelecidos na Lei de Direitos Autorais Digital do Milênio dos Estados Unidos (U.S. Digital Millennium Copyright Act).</p>
                <p>Fornecemos informações para ajudar os detentores de direitos autorais a gerenciarem sua propriedade intelectual on-line. Caso você entenda que alguém está violando seus direitos autorais e quiser nos notificar, você pode encontrar informações sobre o envio de notificações e sobre a política d<?php echo $app ?> para respondê-las pelo <a href="<?php echo Yii::app()->createUrl('site/contact') ?>">formulário de Feedback.</a></p>

                <h2 id="toc-content">Seu Conteúdo em nossos Serviços</h2>
                <p>Alguns de nossos Serviços permitem que você envie conteúdo. Você mantém a propriedade de quaisquer direitos de propriedade intelectual que você detenha sobre aquele conteúdo. Em resumo, aquilo que pertence a você, permanece com você.</p>
                <p>Quando você faz upload ou de algum modo envia conteúdo a nossos Serviços, você concede <?php echo $app ?> (e àqueles com quem trabalhamos) uma licença mundial para usar, hospedar, armazenar, reproduzir, modificar, criar obras derivadas (como aquelas resultantes de traduções, adaptações ou outras alterações que fazemos para que seu conteúdo funcione melhor com nossos Serviços), comunicar, publicar, executar e exibir publicamente e distribuir tal conteúdo. Os direitos que você concede nesta licença são para os fins restritos de operação, promoção e melhoria de nossos Serviços e de desenvolver novos Serviços. Essa licença perdura mesmo que você deixe de usar nossos Serviços (por exemplo, uma listagem de projetos que você adicionou <?php echo $app ?>). Alguns Serviços podem oferecer-lhe modos de acessar e remover conteúdos que foram fornecidos para aquele Serviço. Além disso, em alguns de nossos Serviços, existem termos ou configurações que restringem o escopo de nosso uso do conteúdo enviado nesses Serviços. Certifique-se de que você tem os direitos necessários para nos conceder a licença de qualquer conteúdo que você enviar a nossos Serviços.</p>
                <p>Você pode encontrar mais informações sobre como <?php echo $app ?> usa e armazena conteúdo na política de privacidade. Se você enviar comentários ou sugestões sobre nossos Serviços, podemos usar seus comentários ou sugestões sem obrigação para você.</p>

                <h2 id="toc-software">Sobre Software em nossos Serviços</h2>
                <p>Quando um Serviço exige ou inclui software disponível para download, tal software poderá atualizar-se automaticamente em seu dispositivo se uma nova versão ou recurso estiver disponível. Alguns Serviços podem permitir que você ajuste suas configurações de atualizações automáticas.</p>
                <p>O Google concede a você uma licença pessoal, mundial, não exclusiva, intransferível e isenta de royalties para o uso do software fornecido pel<?php echo $app ?> como parte dos Serviços. Essa licença tem como único objetivo permitir que você use e aproveite o benefício dos Serviços, tal como fornecidos pel<?php echo $app ?>, da forma permitida por estes termos. Você não poderá copiar, modificar, distribuir, vender ou alugar qualquer parte de nossos Serviços ou o software incluso, nem poderá fazer engenharia reversa ou tentar extrair o código fonte desse software, exceto nos casos em que a legislação proibir tais restrições, ou quando você tiver nossa permissão por escrito.</p>
                <p>Software de código aberto é importante para nós. Alguns dos softwares usados em nossos Serviços podem ser oferecidos sob uma licença de código aberto que colocaremos a sua disposição. Pode haver disposições na licença de código aberto que substituam expressamente alguns desses termos.</p>

                <h2 id="toc-modification">Como modificar e cancelar nossos Serviços</h2>
                <p>Estamos constantemente alterando e melhorando nossos Serviços. Podemos incluir ou remover funcionalidades ou recursos e podemos também suspender ou encerrar um Serviço por completo.</p>
                <p>Você pode deixar de usar nossos Serviços a qualquer momento, embora fiquemos chateados ao ver você ir embora. O Google também poderá deixar de prestar os Serviços a você ou, incluir ou criar novos limites a nossos Serviços a qualquer momento.</p>
                <p>Acreditamos que você seja o proprietário dos seus dados e que é importante preservar seu acesso a esses dados. Se descontinuarmos um Serviço, quando razoavelmente possível, você será informado com antecedência razoável e terá a chance de retirar as suas informações daquele Serviço.</p>

                <h2 id="toc-warranties-disclaimers">Nossas Garantias e Isenções de Responsabilidade</h2>
                <p>Fornecemos nossos Serviços usando um nível comercialmente razoável de capacidade e cuidado e esperamos que você aproveite seu uso deles. Mas existem algumas coisas que não prometemos sobre nossos Serviços.</p>
                <p>Exceto quando expressamente previsto nestes termos ou em termos adicionais, nem <?php echo $app ?>, nem seus fornecedores ou distribuidores oferecem quaisquer garantias sobre os Serviços. Por exemplo, não nos responsabilizamos pelos conteúdos nos Serviços, por funcionalidades específicas dos Serviços, ou pela confiabilidade, disponibilidade ou capacidade de atender suas necessidades. Fornecemos os serviços “na forma em que estão”.</p>
                <p>Certas jurisdições prevêem de determinadas garantias, como a garantia de comerciabilidade implícita, adequação a uma finalidade específica e não violação. Na medida permitida por lei, excluímos todas as garantias.</p>

                <h2 id="toc-liability">Responsabilidade pelos nossos Serviços</h2>
                <p>Quando permitido por lei, <?php echo $app ?> e os fornecedores ou distribuidores d<?php echo $app ?> não serão responsáveis por perda de lucros, perda de receita, perda de dados, perdas financeiras ou por danos indiretos, especiais, consequenciais, exemplares ou punitivos.</p>
                <p>Na medida permitida por lei, a responsabilidade total d<?php echo $app ?> e de seus fornecedores e distribuidores, para qualquer reclamação sob estes termos, incluindo quaisquer garantias implícitas, limita-se ao valor que você pagou <?php echo $app ?> para usar os Serviços (ou, a nosso critério, para fornecer a você os Serviços novamente).</p>
                <p>Em todos os casos, <?php echo $app ?> e seus fornecedores e distribuidores não serão responsáveis por qualquer perda ou dano que não seja razoavelmente previsível.</p>
                <p>Reconhecemos que, em alguns países, você pode ter direitos legais como consumidor. Caso você esteja usando os Serviços com objetivos pessoais, então nada nestes termos ou em quaisquer termos adicionais limitarão direitos de consumidor que não possam ser renunciados por contrato.</p>

                <h2 id="toc-business-uses">Usos comerciais de nossos Serviços</h2>
                <p>Se você estiver usando nossos Serviços em nome de uma empresa, tal empresa aceita estes termos. Ela isentará de responsabilidade e indenizará <?php echo $app ?> e suas afiliadas, executivos, agentes e trabalhadores de qualquer reivindicação, processo ou ação judicial proveniente de ou relacionado ao uso dos Serviços ou à violação destes termos, incluindo qualquer responsabilidade ou despesa resultante de reivindicações, perdas, danos, processos, julgamentos, custos de litígio e honorários advocatícios.</p>

                <h2 id="toc-about">Sobre estes Termos</h2>
                <p>Podemos modificar estes termos ou quaisquer termos adicionais que sejam aplicáveis a um Serviço para, por exemplo, refletir alterações da lei ou mudanças em nossos Serviços. Você deve consultar os termos regularmente. Postaremos avisos sobre modificações nesses termos nesta página. Publicaremos um aviso de alteração sobre os termos adicionais dentro do Serviço aplicável. As alterações não serão aplicadas retroativamente e entrarão em vigor pelo menos quatorze dias após sua publicação. Entretanto, alterações a respeito de novas funcionalidades de um Serviço ou alterações feitas por razões legais entrarão em vigor imediatamente. Se você não concordar com os termos alterados de um Serviço, deve descontinuar o uso desse Serviço.</p>
                <p>Em caso de conflito entre estes termos e os termos adicionais, os termos adicionais prevalecerão com relação a esse conflito.</p>
                <p>Estes termos regem a relação entre <?php echo $app ?> e você. Eles não criam quaisquer direitos para terceiros.</p>
                <p>Caso você não cumpra estes termos e nós não tomemos providências imediatas, isso não significa que estamos renunciando a quaisquer direitos que possamos ter (como tomar providências futuras).</p>
                <p>Caso uma condição específica destes termos não seja executável, isso não prejudicará quaisquer outros termos.</p>
                <p>Os tribunais de alguns países não aplicarão a lei da Califórnia a alguns tipos de disputas. Se você reside em um desses países, então, quando a legislação da Califórnia não puder ser aplicada, a legislação de seu país será aplicada às disputas relacionadas com estes termos. Nos outros casos, você concorda com a aplicação das leis da Califórnia, EUA, excluindo as normas da Califórnia sobre conflitos de leis, a quaisquer disputas decorrentes de ou relacionadas com estes termos ou Serviços. Da mesma forma, caso as leis em seu país não permitam que você concorde com a jurisdição e foro dos tribunais de Santa Clara, Califórnia, EUA, então jurisdição e foro locais serão aplicados às disputas relacionadas com estes termos. Nos outros casos todas as reclamações decorrentes de ou relacionadas com esses termos ou Serviços serão litigadas exclusivamente em tribunais estaduais ou federais da Comarca de Santa Clara, Califórnia, EUA e você e <?php echo $app ?> autorizam a jurisdição pessoal nesses tribunais.</p>
            </div>
        </div>
    </section>
</div>